name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: .next/    # Or your actual output folder (e.g., "out" if using static export)

  deploy:
    needs: build
    runs-on: [self-hosted, linux]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
          path: /home/ubuntu/deploy-temp/frontend

      - name: Copy to deploy folder
        run: |
          rm -rf /home/ubuntu/deploy/frontend/*
          cp -r /home/ubuntu/deploy-temp/frontend/* /home/ubuntu/deploy/frontend/

      - name: Restart Frontend Service
        run: |
          pm2 reload all || pm2 start npm --name "my-frontend-app" -- start
