name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: |
            .next
            package.json
            next.config.js
            public

  deploy:
    needs: build
    runs-on: [self-hosted, linux]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
          path: /home/ubuntu/deploy-temp/frontend

      - name: Copy to deploy folder
        run: |
          rm -rf /home/ubuntu/deploy/frontend/*
          cp -r /home/ubuntu/deploy-temp/frontend/* /home/ubuntu/deploy/frontend/

      - name: Install production dependencies
        working-directory: /home/ubuntu/deploy/frontend
        run: npm install --omit=dev --legacy-peer-deps

      - name: Restart Frontend Service
        working-directory: /home/ubuntu/deploy/frontend
        run: |
          pm2 list | grep my-frontend-app && pm2 restart my-frontend-app || pm2 start npm --name "my-frontend-app" -- start
